---
- hosts: all
  become: yes
  gather_facts: yes

  tasks: 
    - name: Install nginx
      apt: 
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family=="Debian"

    - name: Install Nginx on RedHat family
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_os_family=="RedHat"
     

    - name: Create user
      user:
        name: Eden
        comment: "Eden TEMTA"
        shell: /bin/bash

    - name: Create group
      group:
        name: CloudTeam
        state: present

    - name: Create index file
      file:
        path: /var/www/html/index.html
        state: touch

    - name: Copy content to index
      copy: 
        dest: /var/www/html/index.html
        content: '<h1>This is created using ansible</h1>'
